-- Custom keymaps layered on top of LazyVim's defaults.

vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>", { desc = "Clear search highlights" })
vim.keymap.set("n", "<leader>ej", vim.diagnostic.goto_next, { desc = "Next diagnostic" })
vim.keymap.set("n", "<leader>ek", vim.diagnostic.goto_prev, { desc = "Previous diagnostic" })
vim.keymap.set("n", "<leader>q", vim.diagnostic.setloclist, { desc = "Open diagnostic quickfix list" })

vim.keymap.set("x", "<leader>a", function()
  vim.cmd('normal! "+y')
  vim.fn.jobstart({ "herdr", "plugin", "action", "invoke", "annotate.capture" })
end, { desc = "Annotate selection in Herdr" })

-- Keep the old TypeScript shortcuts, now backed by vtsls code actions.
vim.keymap.set("n", "<leader>tm", function()
  LazyVim.lsp.action["source.addMissingImports.ts"]()
end, { desc = "TS add missing imports" })
vim.keymap.set("n", "<leader>to", function()
  LazyVim.lsp.action["source.organizeImports"]()
end, { desc = "TS organize imports" })

vim.keymap.set("n", "<leader>t", "", { desc = "+test" })
vim.keymap.set("n", "<leader>tt", function()
  require("neotest").output_panel.clear()
  require("neotest").run.run(vim.fn.expand("%"))
end, { desc = "Run file" })
vim.keymap.set("n", "<leader>tT", function()
  require("neotest").output_panel.clear()
  require("neotest").run.run(vim.uv.cwd())
end, { desc = "Run all test files" })
vim.keymap.set("n", "<leader>tr", function()
  require("neotest").output_panel.clear()
  require("neotest").run.run()
end, { desc = "Run nearest test" })
vim.keymap.set("n", "<leader>tl", function()
  require("neotest").output_panel.clear()
  require("neotest").run.run_last()
end, { desc = "Run last test" })
vim.keymap.set("n", "<leader>ts", function()
  require("neotest").summary.toggle()
end, { desc = "Toggle test summary" })
vim.keymap.set("n", "<leader>tO", function()
  require("neotest").output_panel.open({ auto_close = true, last_run = true })
end, { desc = "Show test output" })
vim.keymap.set("n", "<leader>tS", function()
  require("neotest").run.stop()
end, { desc = "Stop test" })
vim.keymap.set("n", "<leader>tw", function()
  require("neotest").watch.toggle(vim.fn.expand("%"))
end, { desc = "Toggle test watch" })

vim.keymap.set("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Exit terminal mode" })
vim.keymap.set("n", "<C-h>", "<C-w><C-h>", { desc = "Move focus left" })
vim.keymap.set("n", "<C-l>", "<C-w><C-l>", { desc = "Move focus right" })
vim.keymap.set("n", "<C-j>", "<C-w><C-j>", { desc = "Move focus down" })
vim.keymap.set("n", "<C-k>", "<C-w><C-k>", { desc = "Move focus up" })
